#!/usr/bin/env python3
"""Regenerate mock state JSON files for Pedro Dashboard (Etap 1).

Idempotent. Writes all 8 widget state files to app/state/.

Usage:
    python3 scripts/write-mock-state.py            # overwrite with current time
    python3 scripts/write-mock-state.py --check    # exit 1 if any file is missing or stale
    python3 scripts/write-mock-state.py --out DIR  # write to a different state dir

Atomic write: temp file in the same directory + os.replace(). Never leaves
half-written JSON in app/state/.

All payloads are mock-only and contain no secrets, raw logs, or private
Discord content. Privacy mode default = "private" (MVP) and can be overridden
by DASHBOARD_PRIVACY_MODE env var.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
APP_DIR = PROJECT_ROOT / "app"
DEFAULT_STATE_DIR = APP_DIR / "state"

PRIVACY_MODE = os.environ.get("DASHBOARD_PRIVACY_MODE", "private")


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _is_stale(updated_at: object, ttl_seconds: object) -> bool:
    try:
        ttl = float(ttl_seconds)
    except (TypeError, ValueError):
        return False
    if ttl <= 0:
        return False
    if not isinstance(updated_at, str) or not updated_at:
        return True
    try:
        stamp = datetime.fromisoformat(updated_at.replace("Z", "+00:00"))
    except ValueError:
        return True
    if stamp.tzinfo is None:
        stamp = stamp.replace(tzinfo=timezone.utc)
    return (datetime.now(timezone.utc) - stamp.astimezone(timezone.utc)).total_seconds() > ttl


def _atomic_write(path: Path, payload: dict) -> None:
    """Write JSON atomically: temp file in same dir + flush + replace."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
        f.write("\n")
        f.flush()
        try:
            os.fsync(f.fileno())
        except OSError:
            pass
    os.replace(tmp, path)


def _envelope(widget: str, status: str, ttl: int, data: dict, error: dict | None = None) -> dict:
    return {
        "status": status,
        "updated_at": _now_iso(),
        "ttl_seconds": ttl,
        "privacy_mode": PRIVACY_MODE,
        "data": data,
        "error": error,
    }


# ---- widget payloads -------------------------------------------------------


def widget_dashboard() -> dict:
    return _envelope(
        "dashboard",
        "ok",
        30,
        {
            "title": "Pedro Dashboard",
            "etap": 1,
            "layout": "2x2",
            "target_resolution": "1920x1200",
            "panels": {
                "upper_left": "current_focus",
                "upper_right": "alerts",
                "lower_left": "voice_console",
                "lower_right": "decisions",
            },
            "panels_secondary": {"header_strip": ["system", "hermes", "openviking"]},
            "note": "Mock data generated by scripts/write-mock-state.py",
        },
    )


def widget_system() -> dict:
    return _envelope(
        "system",
        "ok",
        30,
        {
            "host": "imac-hermes",
            "os": "Debian GNU/Linux 13 (trixie)",
            "kernel": "6.12.63+deb13-amd64",
            "python": "3.13.5",
            "ram_total_mb": 5943,
            "ram_available_mb": 4400,
            "swap_total_mb": 2048,
            "swap_used_mb": 347,
            "disk_total_gb": 1840,
            "disk_used_gb": 23,
            "disk_available_gb": 1700,
            "load_avg_1": 0.18,
            "load_avg_5": 0.22,
            "load_avg_15": 0.20,
            "uptime_seconds": int(time.time() - 7384),
            "dashboard_process_alive": True,
            "browser": "google-chrome",
            "display": "DISPLAY=:0 1920x1200 LVDS",
            "no_systemd": True,
            "note": "Mock summary for MVP. Real probes land in Etap 3.",
        },
    )


def widget_hermes() -> dict:
    return _envelope(
        "hermes",
        "ok",
        60,
        {
            "service": "hermes-gateway",
            "watchdog_daemon": "running",
            "gateway_process": "running",
            "ui_endpoint_local": "http://127.0.0.1:40219",
            "logs_path": "~/.hermes/logs/",
            "last_health_check": _now_iso(),
            "note": "Public availability only. No raw logs, no session text.",
        },
    )


def widget_openviking() -> dict:
    return _envelope(
        "openviking",
        "ok",
        60,
        {
            "service": "openviking",
            "endpoint": "http://127.0.0.1:1933",
            "health_endpoint": "http://127.0.0.1:1933/health",
            "health_status": "ok",
            "healthy": True,
            "version": "0.3.14",
            "auth_mode": "dev",
            "last_health_check": _now_iso(),
            "note": "Health only — no private content without explicit privacy-aware command.",
        },
    )


def widget_current_focus() -> dict:
    return _envelope(
        "current_focus",
        "ok",
        120,
        {
            "headline": "Etap 1 — minimalny skeleton cockpitu",
            "project": "pedro_dashboard",
            "owner": "iMac-Hermes / Pedro primary",
            "phase": "Etap 1 of 6",
            "next_milestone": "Etap 2: atomic JSON writes + stany ok/stale/error/empty/disabled",
            "active_tasks": [
                "Wykonać Etap 1 MVP skeleton (server + static + state + mock).",
                "Zweryfikować endpointy /api/health i /api/state.",
                "Przygotować prompty Codexa dla Etap 2.",
            ],
            "blockers": [],
            "note": "Brak blokad w Etap 1.",
        },
    )


def widget_alerts() -> dict:
    return _envelope(
        "alerts",
        "ok",
        30,
        {
            "alerts": [
                {
                    "id": "etap1-info",
                    "severity": "info",
                    "title": "MVP skeleton gotowy",
                    "detail": "Serwer nasłuchuje na 127.0.0.1:17890. Brak realnych integracji.",
                    "since": _now_iso(),
                }
            ],
            "summary": {"info": 1, "warning": 0, "error": 0, "critical": 0},
            "note": "Mock alerts only.",
        },
    )


def widget_decisions() -> dict:
    return _envelope(
        "decisions",
        "ok",
        300,
        {
            "decisions": [
                {
                    "id": "D-001",
                    "title": "MVP runtime: Python stdlib + static HTML/CSS/vanilla JS",
                    "status": "locked",
                    "scope": "Etap 1+",
                    "summary": "Bez Node/React/Electron w MVP.",
                },
                {
                    "id": "D-002",
                    "title": "Bind dashboard: 127.0.0.1:17890",
                    "status": "locked",
                    "scope": "Etap 1+",
                    "summary": "Brak ekspozycji na LAN bez świadomej decyzji.",
                },
                {
                    "id": "D-003",
                    "title": "LL panel = Pedro Voice Console",
                    "status": "locked",
                    "scope": "MVP",
                    "summary": "MVP: tylko mock voice_console.json.",
                },
                {
                    "id": "D-004",
                    "title": "Privacy modes: normal | private | guest",
                    "status": "planned",
                    "scope": "Etap 5",
                    "summary": "MVP domyślnie private.",
                },
                {
                    "id": "D-005",
                    "title": "Sports widget: siatkówka PL, free-first",
                    "status": "planned",
                    "scope": "Po MVP",
                    "summary": "PZPS / Volleyball World / CEV + TheSportsDB.",
                },
            ],
            "note": "Skróty decyzji bez treści prywatnych.",
        },
    )


def widget_voice_console(state: str = "idle", summary: str = "Brak aktywnej komendy.") -> dict:
    """Voice console mock. Uses Pedro Voice Console contract (03_*.md)."""
    return {
        "status": "ok",
        "updated_at": _now_iso(),
        "ttl_seconds": 60,
        "privacy_mode": PRIVACY_MODE,
        "voice": {
            "mode": "mock",
            "state": state,
            "wake_phrase": "hej Pedro",
            "mic_status": "unknown",
            "stt_status": "not_configured",
            "runner_status": "not_configured",
        },
        "utterance": {
            "partial": "",
            "final": "",
            "language": "pl",
            "confidence": None,
        },
        "activity": {
            "label": "Gotowe" if state == "idle" else state,
            "detail": f"Mock voice: {state}.",
            "spinner": state not in ("idle", "speaking_or_result", "error", "privacy_blocked", "disabled"),
        },
        "result": {
            "summary": summary,
            "requires_user_action": False,
            "clarifying_question": None,
        },
        "error": {"code": None, "message_public": None, "debug_ref": None},
    }


# ---- new visual v1 widgets (three-zone media dashboard) ----------------


def widget_weather() -> dict:
    return _envelope(
        "weather",
        "ok",
        600,
        {
            "city": "Kraków",
            "source": "open-meteo (mock)",
            "current": {
                "temp_c": 18.0,
                "feels_like_c": 18.0,
                "condition": "Częściowe zachmurzenie",
                "wind_kmh": 13.0,
                "humidity_pct": 62.0,
                "precip_pct": 10.0,
            },
            "hourly": [
                {"hour": "08:00", "temp_c": 16.0, "condition": "Częściowe zachmurzenie"},
                {"hour": "11:00", "temp_c": 18.0, "condition": "Częściowe zachmurzenie"},
                {"hour": "14:00", "temp_c": 20.0, "condition": "Słonecznie"},
                {"hour": "17:00", "temp_c": 21.0, "condition": "Słonecznie"},
                {"hour": "20:00", "temp_c": 17.0, "condition": "Pochmurno"},
            ],
        },
    )


def widget_route() -> dict:
    return _envelope(
        "route",
        "ok",
        600,
        {
            "city": "Kraków",
            "start_label": "Dom",
            "end_label": "Praca",
            "time_window": "7:45 – 8:25",
            "duration_min": 40,
            "via": "A4",
            "note": "Najszybsza trasa",
            "distance_km": 24.6,
        },
    )


def widget_calendar() -> dict:
    return _envelope(
        "calendar",
        "ok",
        300,
        {
            "date_human": "Piątek, 23 maja 2025",
            "events": [
                {"time": "08:30", "title": "Stand-up",              "color": "var(--blue)"},
                {"time": "10:00", "title": "Spotkanie projektowe",  "color": "var(--red)"},
                {"time": "12:30", "title": "Lunch",                 "color": "var(--green)"},
                {"time": "15:00", "title": "Przegląd wyników",      "color": "var(--orange)"},
                {"time": "17:00", "title": "Trening siatkówki",     "color": "var(--yellow)"},
            ],
            "more_count": 2,
        },
    )


def widget_volleyball() -> dict:
    return _envelope(
        "volleyball",
        "ok",
        600,
        {
            "team_label": "Polska",
            "men": [
                {
                    "date": "2025-05-24", "date_human": "24.05.2025", "time": "Sobota, 17:00",
                    "home": {"name": "Polska", "flag": "pl"},
                    "away": {"name": "Brazylia", "flag": "br"},
                    "competition": "VNL 2025", "location": "Łódź",
                },
                {
                    "date": "2025-05-25", "date_human": "25.05.2025", "time": "Niedziela, 14:00",
                    "home": {"name": "Polska", "flag": "pl"},
                    "away": {"name": "Japonia", "flag": "jp"},
                    "competition": "VNL 2025", "location": "Łódź",
                },
                {
                    "date": "2025-05-31", "date_human": "31.05.2025", "time": "Sobota, 20:30",
                    "home": {"name": "Polska", "flag": "pl"},
                    "away": {"name": "Włochy", "flag": "it"},
                    "competition": "VNL 2025", "location": "Osaka (JPN)",
                },
                {
                    "date": "2025-06-01", "date_human": "01.06.2025", "time": "Niedziela, 13:00",
                    "home": {"name": "Polska", "flag": "pl"},
                    "away": {"name": "Argentyna", "flag": "ar"},
                    "competition": "VNL 2025", "location": "Osaka (JPN)",
                },
                {
                    "date": "2025-06-11", "date_human": "11.06.2025", "time": "Środa, 18:00",
                    "home": {"name": "Polska", "flag": "pl"},
                    "away": {"name": "Serbia", "flag": "rs"},
                    "competition": "VNL 2025", "location": "Gdańsk",
                },
            ],
            "women": [
                {
                    "date": "2025-06-04", "date_human": "04.06.2025", "time": "Środa, 20:00",
                    "home": {"name": "Polska", "flag": "pl"},
                    "away": {"name": "USA",    "flag": "us"},
                    "competition": "VNL 2025", "location": "Antalya (TUR)",
                },
                {
                    "date": "2025-06-07", "date_human": "07.06.2025", "time": "Sobota, 17:00",
                    "home": {"name": "Polska", "flag": "pl"},
                    "away": {"name": "Chiny",  "flag": "cn"},
                    "competition": "VNL 2025", "location": "Hongkong (CHN)",
                },
                {
                    "date": "2025-06-12", "date_human": "12.06.2025", "time": "Czwartek, 19:30",
                    "home": {"name": "Polska", "flag": "pl"},
                    "away": {"name": "Francja","flag": "fr"},
                    "competition": "VNL 2025", "location": "Łódź",
                },
                {
                    "date": "2025-06-15", "date_human": "15.06.2025", "time": "Niedziela, 18:00",
                    "home": {"name": "Polska", "flag": "pl"},
                    "away": {"name": "Niemcy", "flag": "de"},
                    "competition": "VNL 2025", "location": "Łódź",
                },
            ],
            "note": "Mock terminarza VNL 2025 (wolny feed). Docelowo: PZPS / Volleyball World / CEV.",
        },
    )


def widget_media() -> dict:
    return _envelope(
        "media",
        "ok",
        120,
        {
            # Polsat Sport live transmission card
            "transmission": {
                "channel": "Polsat Sport",
                "title": "Polska — Brazylia",
                "competition": "VNL 2025",
                "live": True,
                "player_name": "Bartosz Kurek",
                "jersey_number": 11,
                "progress_pct": 32,
            },
            # Google Photos slideshow card
            "slideshow": {
                "album": "Wakacje 2024",
                "total": 42,
                "current": 10,
                "provider": "google_photos (mock)",
            },
            # LL TBD placeholder
            "tbd": {
                "title": "Miejsce na Twoje pomysły",
                "subtitle": "Powiedz Hermesowi, co chcesz tu zobaczyć.",
                "icon": "stack",
            },
        },
    )


def widget_ll_tbd() -> dict:
    return _envelope(
        "ll_tbd",
        "ok",
        600,
        {
            "title": "Miejsce na Twoje pomysły",
            "subtitle": "Powiedz Hermesowi, co chcesz tu zobaczyć.",
            "icon": "stack",
        },
    )


# ---- driver ----------------------------------------------------------------


WIDGETS = {
    "dashboard.json": widget_dashboard,
    "system.json": widget_system,
    "hermes.json": widget_hermes,
    "openviking.json": widget_openviking,
    "current_focus.json": widget_current_focus,
    "alerts.json": widget_alerts,
    "decisions.json": widget_decisions,
    "voice_console.json": lambda: widget_voice_console("idle"),
    # Live-owned widgets are written by refresh-*.py connectors below, not by
    # mock baseline. Keeping them out of the baseline prevents visible races
    # where the 20s refresher briefly shows stale mock values before live probes
    # overwrite them again.
    # - weather.json -> refresh-weather-status.py
    # - route.json -> refresh-route-status.py
    # - calendar.json -> refresh-kamila-calendar.py
    # - volleyball.json -> refresh-match-calendar.py
    # - media.json slideshow -> refresh-photos-slideshow.py
    "ll_tbd.json": widget_ll_tbd,
}


def write_all(state_dir: Path) -> list[Path]:
    written: list[Path] = []
    for name, fn in WIDGETS.items():
        path = state_dir / name
        _atomic_write(path, fn())
        written.append(path)
    return written


def check_all(state_dir: Path) -> int:
    """Return count of missing, invalid, or stale files. Used by --check."""
    problems: list[str] = []
    for name in WIDGETS:
        path = state_dir / name
        if not path.exists():
            problems.append(f"missing:{name}")
            continue
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            problems.append(f"invalid:{name}:{exc}")
            continue
        if not isinstance(payload, dict):
            problems.append(f"invalid:{name}:payload_not_object")
            continue
        if _is_stale(payload.get("updated_at"), payload.get("ttl_seconds")):
            problems.append(f"stale:{name}")
    if problems:
        print("problems: " + ", ".join(problems), file=sys.stderr)
    return len(problems)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="verify state files exist; exit 1 if any missing")
    parser.add_argument("--out", default=str(DEFAULT_STATE_DIR), help="output state directory")
    args = parser.parse_args(argv)

    state_dir = Path(args.out).resolve()
    if args.check:
        missing = check_all(state_dir)
        if missing:
            print(f"FAIL: {missing} state file(s) missing in {state_dir}", file=sys.stderr)
            return 1
        print(f"OK: {len(WIDGETS)} state files present, valid, and fresh in {state_dir}")
        return 0

    state_dir.mkdir(parents=True, exist_ok=True)
    written = write_all(state_dir)
    print(f"wrote {len(written)} mock state files to {state_dir}")
    for p in written:
        print(f"  - {p.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
